## <strong> 1. Numpy Basic </strong>

<h3> <strong>1.1 1D with Numpy </strong> </h3>

Numpy로 1차원 텐서인 벡터를 만들어보자.

In [30]:
import numpy as np

In [3]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


벡터의 차원과 크기를 출력해보자.

In [4]:
print('dim of t:', t.ndim)    # ndim: 텐서가 몇 차원인지 출력해준다.
print('shape of t', t.shape)  # shape: 텐서의 크기를 출력한다.

dim of t: 1
shape of t (7,)


넘파이의 텐서는 **인덱스를 이용해 원소에 접근할 수 있다.**

In [5]:
print('t[0] t[1] t[-1]:', t[0], t[1], t[-1])

t[0] t[1] t[-1]: 0.0 1.0 6.0


또한 **슬라이싱(Slicing)**을 이용해 범위를 지정하여 원소를 불러올 수 있다.

In [7]:
print('t[2:5] t[:2]]:', t[2:5], t[:2])

t[2:5] t[:2]]: [2. 3. 4.] [0. 1.]


<h3> <strong>1.2 2D with Numpy </strong> </h3>

Numpy로 2차원 행렬을 만들어보자.

In [8]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [9]:
print('dim of t:', t.ndim)    # ndim: 텐서가 몇 차원인지 출력해준다.
print('shape of t', t.shape)  # shape: 텐서의 크기를 출력한다.

dim of t: 2
shape of t (4, 3)


## <strong> 2. PyTorch Tensor Allocation </strong>

먼저 torch를 임포트하자.

In [2]:
import torch

<h3> <strong> 2.1 1D with PyTorch </strong> </h3>

파이터치로 벡터를 만들어보자.

In [11]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


벡터의 차원과 크기를 출력해보자.

In [12]:
print(t.dim())  # dim: 텐서가 몇 차원인지 출력해준다.
print(t.shape)  # shape: 텐서의 크기를 출력한다.
print(t.size()) # size: 텐서의 크기를 출력한다.

1
torch.Size([7])
torch.Size([7])


원소에 접근하려면 인덱싱, 슬라이싱 등 Numpy와 동일하게 접근할 수 있다.

<h3> <strong> 2.2 2D with PyTorch </strong> </h3>

2차원 행렬을 만들어보자.

In [13]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [14]:
print(t.dim())  # dim: 텐서가 몇 차원인지 출력해준다.
print(t.shape)  # shape: 텐서의 크기를 출력한다.
print(t.size()) # size: 텐서의 크기를 출력한다.

2
torch.Size([4, 3])
torch.Size([4, 3])


<h3> <strong> 2.3 Broadcasting </strong> </h3>

**크기가 다른 두 텐서를 자동으로 크기를 맞춰 연산을 수행해주는 기능**을 Broadcasting이라고 한다.

아래의 경우 두 텐서의 크기는 동일하므로 연산이 올바르게 수행된다.

In [15]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


하지만 아래의 경우 벡터와 스칼라의 덧셈 연산이 수행된다. 

In [16]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


두 벡터간의 덧셈에서도 브로드캐스팅이 가능하다.

In [17]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## <strong> 3. 자주 사용되는 기능들 </strong>


<h3> <strong> (1) Matrix Multiplication Vs. Multiplication</strong> </h3>

행렬로 곱셈을 하려면 행렬 곱셈(.matmul) 혹은 원소 별 곱셈(.mul)을 사용하면 된다. <br>
아래는 matmul()을 사용해 수행한 행렬 곱이다.

In [4]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


위 처럼 행렬 곱이 아니라 element-wise 곱셈이 존재한다. <br>
동일한 크기의 행렬이 동일한 위치에 있는 원소끼리 곱하는 것을 의미한다. <br>
'*' 혹은 mul()을 통해 수행할 수 있다.

In [5]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


<h3> <strong> (2) Mean </strong> </h3>

평균을 구하려면 .mean() 메서드를 사용하면 된다.

In [6]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


이번에는 2차원 행렬의 평균을 구해보자.

In [8]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())

tensor(2.5000)


위처럼 2차원 행렬에 .mean()을 적용하면 모든 원소의 평균을 구해준다. <br>
이번에는 dim(차원)을 인자로 전달해보자.

In [9]:
print(t.mean(dim=0))

tensor([2., 3.])


dim=0이라는 것은 첫번째 차원인 **행**을 의미한다. <br>
그리고 인자로 dim을 준다면 해당 차원을 제거한다는 의미이다. <br>
즉, 행렬에서 '열'만 남기게 된다. <br>
이번에는 dim=1을 전달해보자.

In [10]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


예상대로 **(모든 열을 제거해서)** 모든 행의 평균을 구해준다.

<h3> <strong> (3) Sum</strong> </h3>

덧셈은 평균과 연산 방법, 인자가 동일하다.

In [11]:
t = torch.FloatTensor([[1, 2], [3, 4]])

print(t.sum()) # 전체 원소의 합 출력
print(t.sum(dim=0)) # (1+3, 2+4) / 행 제거
print(t.sum(dim=1)) # (1+2, 3+4) / 열 제거
print(t.sum(dim=-1)) # (1+2, 3+4) / 열 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


<h3> <strong> (4) Max와 ArgMax </strong> </h3>

**Max는 원소의 최대값을 리턴**하고, **ArgMax는 최대값을 가진 인덱스를 리턴**한다. <br>
먼저 .max를 사용해보자.

In [12]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max())

tensor(4.)


이번에는 dim=0을 전달해보자.

In [13]:
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


위처럼 max에 dim 인자를 주면 argmax도 함께 리턴한다. <br>
이때 max혹은 argmax만 리턴받고 싶다면 아래처럼 리턴값에 인덱스를 부여하면 된다.

In [15]:
print('Max:', t.max(dim=0)[0])
print('Argmax:', t.max(dim=0)[1])

Max: tensor([3., 4.])
Argmax: tensor([1, 1])


만약 각 행의 최대값을 보고 싶다면 dim=1을 인자로 전달하면 된다.

In [16]:
print(t.max(dim=1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


<h3> <strong> (5) View </strong> </h3>

.view()를 사용하면 원소의 수를 유지하면서 텐서의 크기를 변경할 수 있다. <br> numpy의 reshape() 메서드와 동일한 역할을 한다.

먼저 3차원 텐서를 만들어보자.


In [19]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

ft 텐서에 view를 사용해 2차원 행렬로 바꿔보자.

In [20]:
print(ft.view([-1, 3])) # ft 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


이번에는 3차원 텐서에서 차원은 유지하고 형태를 바꿔보자.

In [21]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


<h3> <strong> (6) Squeeze </strong> </h3>

Squeeze는 차원이 1인 경우 해당 차원을 제거한다. <br>
$(3 \times 1)$ 크기의 2차원 텐서르 만들고 1차원 텐서로 바꿔보자.

In [22]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().shape)

torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


<h3> <strong> (7) Unsqueeze </strong> </h3>

Squeeze와 다르게 특정 위치에 1인 차원을 추가할 수 있다.

In [23]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)
print(ft.unsqueeze(0)) # 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [24]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


<h3> <strong> (8) Type Casting </strong> </h3>

텐서에는 자료형이 존재한다. <br>
예를 들어, 32bit 부동 소수점은 torch.FloatTensor, 64비트 정수는 torch.LongTensor를 사용한다. <br>
torch.cuda.FloatTensor와 같이 GPU 연산을 위한 자료형도 존재한다.

이때 이 **자료형을 변환하는 것을 Type Casting**이라고 한다.

먼저 long 타입의 텐서를 선언하자.

In [25]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


이때 .float()를 붙이면 float형으로 타입이 변경된다.

In [26]:
print(lt.float())

tensor([1., 2., 3., 4.])


이번에는 Byte 타입의 텐서를 만들어보자.

In [27]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


이때 .long()을 사용하면 long 타입의 텐서로 변경되고, float()를 사용하면 float 타입의 텐서로 변경된다.

In [28]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


<h3> <strong> (9) Type Casting </strong> </h3>

먼저 2차원 텐서 2개를 만들어보자.

In [29]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

torch.cat([])통해 연결해보자. <br>
이때 dim을 전달하면 어느 차원으로 늘릴 것인지를 인자로 줄 수 있다.

In [31]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [32]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


위처럼 dim=0을 전달하면 행을 늘려주고 dim=1을 전달하면 열을 늘려준다. <br>


<h3> <strong> (10) Stacking </strong> </h3>

Stacking은 텐서를 연결하는 또 다른 방법이다. <br>
이때 cat보다 Stacking이 더 편할 때가 있는데, 이는 Stacking이 많은 연산을 포함하고 있기 때문이다.

먼저 크기가 같은 3개의 벡터를 만들고 torch.stack을 이용해 합쳐보자.

In [33]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


해당 코드를 torch.cat()으로 수행하려면 아래와 같다.

In [34]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


위처럼 cat에 비해 더 편하게 합칠 수 있다. <br>
Stacking 역시 dim을 인자로 줄 수 있는데 해당 차원이 증가하도록 쌓으라는 의미로 해석할 수 있다.

In [35]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


<h3> <strong> (11) ones/zeros_like </strong> </h3>

이차원 행렬을 만들어보자.

In [36]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(torch.ones_like(x)) # 입력 텐서의 크기와 동일하게 값을 1로 채우기
print(torch.zeros_like(x)) # 입력 텐서의 크기와 동일하게 하면서 값을 0으로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


<h3> <strong> (12) In-place Operation </strong> </h3>

이차원 배열을 만들어보자.

In [37]:
x = torch.FloatTensor([[1, 2], [3, 4]])

곱하기 연산을 한 값과 기존의 값을 출력해보자.

In [38]:
print(x.mul(2.)) # 곱하기 2를 수행한 결과 출력
print(x)         # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


이때 x의 값은 변하지 않은 것을 확인할 수 있다.<br>
x값을 바꾸고 싶다면 연산 뒤에 _를 붙이면 된다.

In [39]:
print(x.mul_(2.)) 
print(x)           

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
