이전까지는 가설, 비용 함수를 직접 정의해서 선형 회귀 모델을 구현했다. <br>
이번에는 파이토치에서 이미 구현된 함수들을 이용해 구현해보자.

## <strong> 1. 단순 선형 회귀 구현하기 </strong>

In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [14]:
torch.manual_seed(1)

데이터를 선언해보자.

In [15]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

**nn.Linear()**를 사용해 선형 회귀 모델을 구현해보자. <br>
인자로는 **입력 차원, 출력 차원**을 넘겨주면 된다.

In [16]:
model = nn.Linear(1, 1)

하나의 독립 변수 x와 출력 y를 가지므로 입력과 출력 차원은 1로 전달했다. <br>
model에는 가중치 W와 편향 b가 저장되어 있다. <br>
이 값들은 **model.parameters()**라는 함수를 사용해 불러올 수 있다.

In [17]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


위 출력에서 첫 번째 값이 W, 두 번째 값이 b에 해당한다. <br>
또한 두 값 모두 학습의 대상이므로 requires_grad=True로 지정되어 있다. <br>

이제 옵티마이저를 정의하자.

In [18]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [19]:
nb_epochs = 2000

for epoch in range(nb_epochs+1):
  # H(x) 계산
  prediction = model(x_train)
  
  # cost 계산
  cost = F.mse_loss(prediction, y_train) # 파이토치에서 제공하는 평균 제곱 오차 함수다.

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 400 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))


Epoch    0/2000 Cost: 13.103541
Epoch  400/2000 Cost: 0.000658
Epoch  800/2000 Cost: 0.000096
Epoch 1200/2000 Cost: 0.000014
Epoch 1600/2000 Cost: 0.000002
Epoch 2000/2000 Cost: 0.000000


훈련된 W와 b를 출력해보자. (각각 2, 0에 가까운 값이 나와야 한다.) <br>

In [20]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


## <strong> 2. 다중 선형 회귀 구현하기 </strong>

위 방식으로 다중 선형 회귀를 구현해보자.

In [21]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

# 데이터 선언
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 모듈 생성
model = nn.Linear(3, 1)

# optimizer 선언
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000

for epoch in range(nb_epochs+1):
  # H(x) 계산
  prediction = model(x_train)

  # cost 계산
  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 400 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.597656
Epoch  400/2000 Cost: 0.220059
Epoch  800/2000 Cost: 0.213413
Epoch 1200/2000 Cost: 0.207967
Epoch 1600/2000 Cost: 0.203484
Epoch 2000/2000 Cost: 0.199769


학습 후의 파라미터들을 확인해보자.

In [22]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]
