In [1]:
import numpy as np

<h4> comparisons </h4>
all & any: Array의 데이터 전부(and)또는 일부(or)가 조건에 만족하는지 여부를 반환한다.

* np.any(a > 5), np.any(a < 0)
* np.all(a > 5), np.all(a < 10)

In [2]:
a = np.arange(10)
# 브로드캐스팅이 일어나서 모든 원소에 해당 조건식을 적용한다.
a < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [3]:
# 모두 True이므로 True 반환
np.all(a < 10)

True

In [4]:
# 하나라도 False이므로 False 반환
np.all(a > 5)

False

In [5]:
# 하나라도 True이므로 True 반환
np.any(a > 5)

True

In [6]:
# 모두 False이므로 False 반환
np.any(a < 0)

False

numpy는 배열의 크기가 동일 할 때 element간 비교 결과를 Boolean type으로 반환한다.

In [7]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [8]:
test_a == test_b

array([False, False, False])

In [9]:
(test_a > test_b).any()

True

**np.logical_and, logical_not, logical_or 함수**로 두 array에 논리 연산자를 사용할 수 있다.

In [10]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [12]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [13]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])

**np.where(), np.isnan(), np.isfinite**

where 함수는 아래와 같은 방식으로 True인 곳과 False인 곳의 값을 원하는 값으로 바꿀 수 있다.

* **np.where(조건식, True를 변환할 값, False를 변환할 값)**

In [14]:
a = np.array([1, 3, 0], float)
np.where(a > 0, 3, 2)

array([3, 3, 2])

where 함수에 아래와 같이 조건식만 전달하면 True인 곳의 인덱스만 추출할 수 있다. **단, 튜플안에 array가 원소로 있는 형태로 반환한다.**

* **np.where(조건식)**

In [15]:
b = np.array([5, 6, 1, 7, 8])
np.where(b > 5)

(array([1, 3, 4]),)

**isnan 함수**는 np.NaN값을 가진 데이터는 True 아닌 값은 False로 반환한다. <br>
**isfinite(a)**는 np.Inf값을 가진 데이터는 True 아닌 값은 False로 반환한다.

In [17]:
c = np.array([1, np.NaN, np.Inf], float)
np.isnan(c)

array([False,  True, False])

In [18]:
np.isfinite(c)

array([ True, False, False])

**np.argmax(), np.argmin()**: array내 최대값 또는 최소값의 index를 반환한다. 

In [19]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
print(np.argmax(a), np.argmin(a))

5 0


axis 매개변수로 축을 지정할 수 있다.

In [22]:
a = np.array([[1, 2, 4, 7], [9, 88, 6, 45], [9, 76, 3, 4]])
print(np.argmin(a, axis = 0), np.argmax(a, axis = 1))

[0 0 2 2] [3 1 1]


**np.argsort()**: 오름차순으로 index를 정렬한다.

In [23]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
a.argsort()

array([0, 1, 7, 2, 3, 4, 6, 5])

In [24]:
a.argsort()[::-1]

array([5, 6, 4, 3, 2, 7, 1, 0])

<h3> boolean & fancy index </h3>

<h4> boolean index </h4>

boolean indexing을 사용하면 특정 조건에 따른 값을 배열 형태로 추출할 수 있다. <br>
Comparison operation 함수들도 모두 사용할 수 있다.


In [27]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [28]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [30]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

<h4> fancy index </h4>

**numpy는 array를 index value로 사용해 값을 추출할 수 있다.**

In [31]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b] # bracket index, b 배열의 값을 index로 하여 a의 값을 추출한다.

array([2., 2., 4., 8., 6., 4.])

In [ ]:
a.take(b) # take 함수: bracket index와 같은 효과

matrix 형태의 데이터도 가능하다.

In [32]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b, c] # b: row index, c: col index

array([ 1.,  4., 16., 16.,  4.])

<h3> numpy data I/O </h3>

**np.loadtxt()**와 **np.savetxt()**를 이용해 text type의 데이터를 읽고 저장할 수 있다. <br>
**np.load()**와 **np.save()**를 이용해 npy파일을 읽고 저장할 수 있다. npy파일은 pickle 형태로 저장된다.

* pickle은 파이썬의 대표적인 데이터 저장 방식이다.(3장 참고)